#!/usr/bin/perl

###########################################
# NOAA PIFSC TurtleWatch script
# This is a perl script to create the TurtleWatch product for leatherbacks and loggerheads
# This version of TurtleWatch appears in the manuscript Howell, E.A., Hoover, A., Benson, S.R., Bailey, H., Polovina, J.J., Seminoff, J.A., & Dutton, P.H. (2015) Enhancing the TurtleWatch product for leatherback sea turtles, a dynamic habitat model for ecosystem-based management. Fisheries Oceanography, 1-12.
#
# There are major differences in this version including the expansion of the map range to 180/230/25/50 and new zones for leatherbacks
# East of 140W is red, the isotherm zones are 62.6 (17C) and 65.3 (18.5C), and 72.3 (22.4C) and 74.1 (23.4C) which form two polygons. 
# - Added command line arguments using GetOpt::Long
# - Changed $nowtime variable to $gactime to calculate time based on the SST file and not localtime if specific file is passed.
#
# This script needs certain files, such as the noaa background which 
# was created in Illustrator.
#
# The TurtleWatch image is built and placed in the xfer directory, where it is automatically transferred to the PIFSC webserver
#
# VERSION HISTORY
# Version 2.0, 06/15/2013, EAH (evan.howell@noaa.gov) - Completely rewritten to add leatherback ranges.
# 1.6, 04/30/2009, EAH - Changed to use GMT 3.4.2
# 1.5, 12/26/2007, EAH - Major change was to expand the spatial range of the TurtleWatch map and to change the recommended zone from all SST < 18.5 to the range 17.5-18.5C.
# 1.0, 12/26/2006, EAH - Initial release of TurtleWatch product
###########################################

use Time::Local;
use Time::Local 'timelocal_nocheck';
use File::Basename;
use POSIX qw(strftime);
use Getopt::Long;

#set up default option values
my $verbose = '';
my $debug = '';
my $gacfile = '';
my $nomail = '';
my $help = '';

GetOptions('help' => \$help, 'verbose|quiet' => \$verbose, 'debug' => \$debug, 'gacfile=s' => \$gacfile, 'nomail' => \$nomail, 'english_only' => \$english_only);

if ($help) {
    print("Usage: makeTurtleWatch [--help] [--verbose|quiet] [-debug] [--nomail] [--english_only] [gacfile=<filename>]\n");
    exit 0;
}

if ($debug) {
    $nomail = 1; #set nomail if in debug mode
    $verbose = 1; #set verbose if in debug mode
    print("***IN DEBUG MODE - NOMAIL AND VERBOSE FLAGS SET***\n");
}

#Set up other variable defaults
$GMTDIR = "/usr/local/gmt/bin";
$WORKDIR = "/home/ehowell/projects/Turtle_Front/TurtleWatch";
$XFERDIR = "/s03/xfer";
$SSTDIR = "/s03/gac/data/3day";

$vector = 90;
$vectorlegend = $vector / 3;
$limit = 5;
$vectorcolor = "75/75/75"; #$vectorcolor = "255/255/255"; #To make white

system("$GMTDIR/gmtset DEGREE_FORMAT 3");
system("$GMTDIR/gmtset BASEMAP_TYPE plain");
system("$GMTDIR/gmtset LABEL_FONT_SIZE 16");
system("$GMTDIR/gmtset COLOR_NAN 255/255/255"); #system("$GMTDIR/gmtset COLOR_NAN 125/125/125"); #grey NANs

#get today's and tomorrow's date
($sec,$min,$hour,$mday,$mon,$year,$wday,$yday,$isdst) = localtime(); $year += 1900; $mon++; 
$nowlocaltime = time(); $tomorrowlocaltime = $nowlocaltime + 60*60*24;
$now_string = strftime("%B %02e, %Y %H:%M%p %Z", localtime);
$tom_string = strftime("%B %02e, %Y 04:00AM %Z", localtime($tomorrowlocaltime)); #Time next TurtleWatch image will be created
$nowtime = sprintf("%4d%03d",$year,$yday);

$subject = "Everything worked fine for English Version $mon/$mday/$year";
$subject_viet = "Everything worked fine for Vietnamese Version $mon/$mday/$year";
$subject_korean = "Everything worked fine for Korean Version $mon/$mday/$year";

print("Using SST file $gacfile\n") if $verbose == 1;
#Check if gacfile provided on command line, otherwise grab latest GAC 3-day file from pampa.
if (!$gacfile) { #match if gacfile is not already provided.
    print("matching gacfile from list\n") if $verbose == 1;
    @gacfiles = `ls $SSTDIR/AG20[1-9]*`;#match file from list, good until 12/31/2099!
    @match = grep /$nowtime/, @gacfiles; 
    $gacfile = $match[0];chomp($gacfile);
} else {
    $gacfile = "$SSTDIR/$gacfile";
}

print("Using SST file $gacfile\n") if $verbose == 1;
$gactime = substr(basename($gacfile), 10,7);# pull second date from gacfile used

if (! -e $gacfile) {
   $subject = "There is no file $gacfile on pampa ${mon}/${mday}/${year}";
   system("mutt -s \"$subject\" Evan.Howell\@noaa.gov < /dev/null") if !$nomail;
   print("$subject\n") if $verbose == 1;
   exit -1;
}

#Call subroutine getuvfiles to find the uvfiles relating to gacfile time.
print("Matching AVISO files to date $gactime\n") if $verbose == 1;
@uvfiles = &getuvfiles($gactime);
print("Using files $ufile and $vfile\n") if $verbose;

$contfile = "cont_65.3_0.xyz";
$psfile = "$WORKDIR/sstexample.ps";
$psfile_viet = "$WORKDIR/sstexample_viet.ps";
$psfile_korean = "$WORKDIR/sstexample_korean.ps";
$pngfile = "sstexample.png" if $debug;
$pngfile = "TW${gactime}_image.png";
$pngfile_viet = "TW${gactime}_image_vm.png";
$pngfile_korean = "TW${gactime}_image_kn.png";
$cptfile = "sst.cpt";

open($tempfile, ">temp.txt");
$shortfile = basename($gacfile);

$temp1 = substr($shortfile,6,3);
$temp2 = substr($shortfile,2,4);
$outtime = timelocal_nocheck(0,0,0,$temp1,0,$temp2);
($second, $minute, $hour, $dayOfMonth, $month, $yearOffset, $dayOfWeek, $dayOfYear, $daylightSavings) = localtime($outtime);
$temp = $yearOffset;
$month = $month +1; $year = $yearOffset + 1900;
$scday = strftime("%d%b%Y", localtime($outtime));

$temp1 = substr($shortfile,14,3);
$temp2 = substr($shortfile,10,4);
$outtime = timelocal_nocheck(0,0,0,$temp1,0,$temp2);
($second, $minute, $hour, $dayOfMonth, $month, $yearOffset, $dayOfWeek, $dayOfYear, $daylightSavings) = localtime($outtime);
$month = $month +1; $year = $yearOffset + 1900;
$ecday = strftime("%d%b%Y", localtime($outtime)); #09Jan2007

print("TODAY: $nowtime MATCH: $shortfile SCDAY: $scday - $ecday GACfile: $gacfile\n") if $verbose;

#Ranges
#$range = "180/215/25/40"; #test range
#$range = "185/210/27.5/37.5"; #TurtleWatch V1.0 range (2006)
#$range = "185/220/27.5/37.5"; # TurtleWatch V1.5 range (2007)
$range = "185/225/20.0/38.0"; # TurtleWatch V2.0 range (2013)

#$twlim1 = "63.4/63.6" #<TW2.0
#$twlim2 = "65.4/65.6" #<TW2.0

$twlim1 = "62.59/62.61"; #TW2.0 17.0C
$twlim2 = "65.29/65.31"; #TW2.0 18.5C
$twlim3 = "72.29/72.31"; #TW2.0 22.4C
$twlim4 = "74.09/74.11"; #TW2.0 23.4C

system("$GMTDIR/grdcut $gacfile -R$range -Gtemp.grd");
system("$GMTDIR/grdmath temp.grd 9 MUL 5 DIV 32 ADD = temp.grd");

system("$GMTDIR/grdfilter temp.grd -R$range -D0 -Fm2 -I0.1/0.1 -Gtemp2.grd");
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -Dcont -Q100 -L$twlim2 -W5/0/0/0 >> temp.ps");
$avgval=`awk '(\$1>190&&\$1<=210) {print \$2}' $contfile  | /home/ehowell/bin/average -s` if (-e $contfile);
system("cp temp2.grd working.grd");

$xoffset = 0.75;
$jrange = 0.18; #(9.8/40)

system("grdmath 1 temp2.grd AND = mask3.grd"); # uncomment to make the mask file

###########################################################################################
#To make opacity mask..
system("$GMTDIR/grdcontour temp2.grd -Jm -R -K -A0.1 -L$twlim1 -Dcont -W12/0/0/0 >> $psfile"); #17.0C contour
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim2 -Dcont -W12/0/0/0 >> $psfile");#18.5C contour
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim3 -Dcont -W12/0/0/0 >> $psfile");#22.4C contour
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim4 -Dcont -W12/0/0/0 >> $psfile");#23.4C contour

#make 17.0-18.5C Mask first
system("cat cont_62.6_0.xyz > $WORKDIR/temp.txt");
system("cat cont_65.3_0.xyz | sort +0 -1 >> $WORKDIR/temp.txt");
system("head -n 1 cont_62.6_0.xyz >> $WORKDIR/temp.txt");

system("$GMTDIR/psbasemap -Jm$jrange -R -X$xoffset -Y3.5 -K -Bf2.0a4/f1.00a2.0WeSn -G255/255/255 > $WORKDIR/mask.ps");
system("$GMTDIR/psclip $WORKDIR/temp.txt -Jm -R -K -O >> $WORKDIR/mask.ps");
system("$GMTDIR/grdimage $WORKDIR/mask.grd -O -K -Jm -R -C$WORKDIR/maskpolar.cpt -R >> $WORKDIR/mask.ps");
system("$GMTDIR/psclip -C -O -K >> $WORKDIR/mask.ps");
system("$GMTDIR/psmask $WORKDIR/temp.txt -R -I0.1/0.1  -Jm -O >> $WORKDIR/mask.ps");
system("convert -density 200x200 -rotate 90 -transparent white $WORKDIR/mask.ps $WORKDIR/mask.png");

#Now make 22.4-23.4C Mask
system("cat cont_72.3_0.xyz > $WORKDIR/temp2.txt");
system("cat cont_74.1_0.xyz | sort +0 -1 >> $WORKDIR/temp2.txt");
system("head -n 1 cont_74.1_0.xyz >> $WORKDIR/temp2.txt");

system("$GMTDIR/psbasemap -Jm$jrange -R -X$xoffset -Y3.5 -K -Bf2.0a4/f1.00a2.0WeSn -G255/255/255 > $WORKDIR/mask2.ps");
system("$GMTDIR/psclip $WORKDIR/temp2.txt -Jm -R -K -O >> $WORKDIR/mask2.ps");
system("$GMTDIR/grdimage $WORKDIR/mask.grd -O -K -Jm -R -C$WORKDIR/maskpolar2.cpt -R >> $WORKDIR/mask2.ps");
system("$GMTDIR/psclip -C -O -K >> $WORKDIR/mask2.ps");
system("$GMTDIR/psmask $WORKDIR/temp2.txt -R -I0.1/0.1  -Jm -O >> $WORKDIR/mask2.ps");
system("convert -density 200x200 -rotate 90 -transparent white $WORKDIR/mask2.ps $WORKDIR/mask2.png");

#mask out box east of 140W #DISABLED 9/28/2013 EAH
#system("$GMTDIR/psbasemap -Jm$jrange -R -X$xoffset -Y3.5 -K -Bf2.0a4/f1.00a2.0WeSn -G255/255/255 > $WORKDIR/mask3.ps");
#system("$GMTDIR/psclip $WORKDIR/e140.txt -Jm -R -K -O >> $WORKDIR/mask3.ps");
#system("$GMTDIR/grdimage $WORKDIR/mask3.grd -O -K -Jm -R -C$WORKDIR/maskpolar2.cpt -R >> $WORKDIR/mask3.ps");
#system("$GMTDIR/psclip -C -O -K >> $WORKDIR/mask3.ps");
#system("$GMTDIR/psmask $WORKDIR/temp2.txt -R -I0.1/0.1  -Jm -O >> $WORKDIR/mask3.ps");
#system("convert -density 200x200 -rotate 90 -transparent white $WORKDIR/mask3.ps $WORKDIR/mask3.png");

####################################################################################

system("$GMTDIR/grdmath $ufile 2 POW $vfile 2 POW ADD SQRT = mag.grd");
system("$GMTDIR/grdclip mag.grd -Sb$limit/NaN -Gmag.grd");
system("$GMTDIR/grdmath $ufile mag.grd OR = u.grd");
system("$GMTDIR/grdmath $vfile mag.grd OR = v.grd");

#system("$GMTDIR/grdfilter temp.grd -R$range -D0 -Fm1 -I0.1/0.1 -Gtemp3.grd");

&buildcptfile;

#Start Plotting image, tee data to regular psfile, and vietnamese psfile
#system("$GMTDIR/psbasemap -Jm$jrange -R$range -X$xoffset -Y3.5 -K -Bf2.0a4/f1.00a2.0WeSn | tee $psfile_viet > $psfile"); Splitting to two files below
#system("$GMTDIR/grdimage temp2.grd -Jm -R -O -K -C$cptfile | tee -a $psfile_viet >> $psfile");
system("$GMTDIR/psbasemap -Jm$jrange -R$range -X$xoffset -Y3.5 -K -Bf2.0a4/f1.00a2.0WeSn | tee $psfile_korean $psfile_viet > $psfile");
system("$GMTDIR/grdimage temp2.grd -Jm -R -O -K -C$cptfile | tee -a $psfile_korean $psfile_viet >> $psfile");

# To add islands...
#system("$GMTDIR/grdcontour /s03/ref/topo62.grd -C5 -L-50.1/25.1 -Jm -R -O -K -W2/0/0/0 >> $psfile");

system("$GMTDIR/grdvector u.grd v.grd -R -Jm -Q0.01/0.05/0.025 -O -K -S$vector -G$vectorcolor | tee -a $psfile_korean $psfile_viet >> $psfile");


#################################################################################
# This section plots the contours...
#
#  62.6 and 65.3 to psfile
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim1 -W5/0/0/0 | tee -a $psfile_korean $psfile_viet >> $psfile"); # was 12
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim2 -W5/0/0/0 | tee -a $psfile_korean $psfile_viet >> $psfile");

#  72.3 and 74.1 to psfile
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim3 -W5/0/0/0 | tee -a $psfile_korean $psfile_viet >> $psfile"); # was 12
system("$GMTDIR/grdcontour temp2.grd -Jm -R -O -K -A0.1 -L$twlim4 -W5/0/0/0 | tee -a $psfile_korean $psfile_viet >> $psfile");

#################################################################################

system("$GMTDIR/pscoast -Jm -O -Di -K -G0/0/0 -R | tee -a $psfile_korean $psfile_viet >> $psfile");
$psxoffset = 3.5;
system("$GMTDIR/psscale -D$psxoffset/-0.8/7/0.15h -L -C$cptfile -K -O -B:\"SST (F)\": | tee -a $psfile_korean $psfile_viet >> $psfile");

$x_1 = 185;
$x_2 = 232;
$x_3 = 190;
$x_4 = 225;
$x_5 = 228;

$y_1 = 40.75;
$y_2 = 19.5;
$y_3 = 17.1;
$y_4 = 17.0;

system("echo $x_1 $y_2 9 0 0 LB Image Created $now_string by EAH. Next projected image date: $tom_string | $GMTDIR/pstext -Jm -D0.08c/-0.47 -R -O -K -N | tee -a >> $psfile_korean $psfile_viet $psfile");
#Write to english file
system("echo $x_1 $y_1 12 0 0 LB Sea Surface Temperature: $scday-$ecday| $GMTDIR/pstext -Jm -R -O -N -K >> $psfile");
system("echo $x_2 $y_1 12 0 0 RB Ocean Currents: $sccday-$eccday| $GMTDIR/pstext -Jm -R -O -N -K >> $psfile");
#Write only dates to Vietnamese and Korean files
system("echo $x_3 $y_1 12 0 0 LB $scday-$ecday| $GMTDIR/pstext -Jm -R -O -N -K | tee -a $psfile_korean >> $psfile_viet");
system("echo $x_2 $y_1 12 0 0 RB $sccday-$eccday| $GMTDIR/pstext -Jm -R -O -N -K | tee -a $psfile_korean >> $psfile_viet");

system("echo $x_4 $y_3 90 .333333| $GMTDIR/psxy -SV0.01/0.05/0.025 -R -G0/0/0 -Jm -O -K -N | tee -a $psfile_korean $psfile_viet >> $psfile");
system("echo $x_5 $y_4 12 0 0 0 $vectorlegend cm/sec | $GMTDIR/pstext -Jm -R -O -K -N | tee -a $psfile_korean $psfile_viet >> $psfile");

#Add datestamps
#system("echo $now_string $tom_string\n");

#system("$GMTDIR/psbasemap -Jm -R$range -Bf2.5a5g5/f1.25a2.5g2.5wesn -O -K >> $psfile");
system("$GMTDIR/gmtset GRID_PEN 0.125pta");
#system("$GMTDIR/psbasemap -Jm -R$range -Bf2.0a4g1.0/f1.00a2.0g1.00wesn -O -K | tee -a $psfile_korean $psfile_viet >> $psfile");
system("$GMTDIR/psbasemap -Jm -R$range -Bf2.0a4g1.0/f1.00a2.0g1.00wesn -O | tee -a $psfile_korean $psfile_viet >> $psfile");

#system("gs $psfile");
#system("convert -density 72x72 -rotate 90 $psfile $WORKDIR/temp.png");

###########################################################################################
#work on english file
system("convert -density 200x200 -rotate 90 $psfile $WORKDIR/temp.png");
system("composite $WORKDIR/noaalogo_bottomleft_200.png $WORKDIR/temp.png $pngfile");
system("composite -dissolve 65% $WORKDIR/mask.png $pngfile $pngfile"); #was 40%
system("composite -dissolve 65% $WORKDIR/mask2.png $pngfile $pngfile"); #was 40%
system("composite -dissolve 85% $WORKDIR/mask3.png $pngfile $pngfile"); #was 40%

#if grdcontour is separate
#system("convert -density 200x200 -transparent white -rotate 90 contpsfile $WORKDIR/temp2.png");
#system("composite $WORKDIR/temp2.png $pngfile $pngfile"); 

system("convert -resize 500x386 $pngfile $WORKDIR/today_mid.png");
system("convert -resize 150x116 $pngfile $WORKDIR/today_thumb.png");

$subject = "Missing contour file!" if (! -e $contfile);

if (! -e $pngfile) {
   $subject = "There is no image file $pngfile on pampa ${mon}/${mday}/${year}";
   system("mutt -s \"$subject\" Evan.Howell\@noaa.gov < /dev/null") if !$nomail;
   exit -1;
}

##########################################################################
# Start the imagemagick conversions
system("cp $pngfile $WORKDIR/today.png");
system("cp $pngfile $XFERDIR/$pngfile");
system("cp $pngfile $XFERDIR/today.png");
system("cp $WORKDIR/today_mid.png $XFERDIR/today_mid.png");
system("cp $WORKDIR/today_thumb.png $XFERDIR/today_thumb.png");

#system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov,orders\@geoeye.com,Walter.Machado\@noaa.gov,sean\@pop-hawaii.com, Andrew.Torres\@noaa.gov < /dev/null") if !$nomail;
#system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov,orders\@geoeye.com,seastarorders\@digitalglobe.com,Walter.Machado\@noaa.gov,sean\@pop-hawaii.com, Andrew.Torres\@noaa.gov < /dev/null") if !$nomail;
#system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov < /dev/null") if !$nomail;
system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov < /dev/null") if !$nomail;
system("display $pngfile") if ($debug);

print("$subject\n") if $verbose;

exit 0 if $english_only;

###########################################################################################
#work on vietnamese file
system("convert -density 200x200 -rotate 90 $psfile_viet $WORKDIR/temp_viet.png");
system("composite $WORKDIR/noaalogo_bottomleft_200_vietnamese.png $WORKDIR/temp_viet.png $pngfile_viet");
system("composite -dissolve 65% $WORKDIR/mask.png $pngfile_viet $pngfile_viet"); #was 40%

#if grdcontour is separate
#system("convert -density 200x200 -transparent white -rotate 90 contpsfile $WORKDIR/temp2.png");
#system("composite $WORKDIR/temp2.png $pngfile $pngfile"); 

system("convert -resize 500x386 $pngfile_viet $WORKDIR/today_viet_mid.png");
system("convert -resize 150x116 $pngfile_viet $WORKDIR/today_viet_thumb.png");

$subject = "Missing contour file!" if (! -e $contfile);

if (! -e $pngfile) {
   $subject = "There is no image file $pngfile_viet on pampa ${mon}/${mday}/${year}";
   system("mutt -s \"$subject\" Evan.Howell\@noaa.gov < /dev/null") if !$nomail;
   print("$subject\n") if $verbose == 1;
   exit -1;
}

##########################################################################
# Start the imagemagick conversions
system("cp $pngfile_viet $WORKDIR/today_viet.png");
system("cp $pngfile_viet $XFERDIR/$pngfile_viet");
system("cp $pngfile_viet $XFERDIR/today_viet.png");
system("cp $WORKDIR/today_viet_mid.png $XFERDIR/today_viet_mid.png");
system("cp $WORKDIR/today_viet_thumb.png $XFERDIR/today_viet_thumb.png");

#system("mutt -s \"$subject_viet\" -a $pngfile_viet Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov,keithsymington\@yahoo.ca,sean\@pop-hawaii.com, Andrew.Torres\@noaa.gov < /dev/null") if !nomail;
#system("mutt -s \"$subject_viet\" -a $pngfile_viet Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov < /dev/null") if !nomail;
#system("mutt -s \"$subject_viet\" -a $pngfile_viet Evan.Howell\@noaa.gov < /dev/null") if !nomail;

print("$subject_viet\n") if $verbose;

###########################################################################################
#work on korean file
system("convert -density 200x200 -rotate 90 $psfile_korean $WORKDIR/temp_korean.png");
system("composite $WORKDIR/noaalogo_bottomleft_200_korean.png $WORKDIR/temp_korean.png $pngfile_korean");
system("composite -dissolve 65% $WORKDIR/mask.png $pngfile_korean $pngfile_korean"); #was 40%

#if grdcontour is separate
#system("convert -density 200x200 -transparent white -rotate 90 contpsfile $WORKDIR/temp2.png");
#system("composite $WORKDIR/temp2.png $pngfile $pngfile"); 

system("convert -resize 500x386 $pngfile_korean $WORKDIR/today_korean_mid.png");
system("convert -resize 150x116 $pngfile_korean $WORKDIR/today_korean_thumb.png");

$subject = "Missing contour file!" if (! -e $contfile);

if (! -e $pngfile) {
   $subject = "There is no image file $pngfile_korean on pampa ${mon}/${mday}/${year}";
   system("mutt -s \"$subject\" Evan.Howell\@noaa.gov < /dev/null") if !$nomail;
   print("$subject\n") if $verbose == 1;
   exit -1;
}

##########################################################################
# Start the imagemagick conversions
system("cp $pngfile_korean $WORKDIR/today_korean.png");
system("cp $pngfile_korean $XFERDIR/$pngfile_korean");
system("cp $pngfile_korean $XFERDIR/today_korean.png");
system("cp $WORKDIR/today_korean_mid.png $XFERDIR/today_korean_mid.png");
system("cp $WORKDIR/today_korean_thumb.png $XFERDIR/today_korean_thumb.png");

#system("mutt -s \"$subject_korean\" -a $pngfile_korean Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov,Andrew.Torres\@noaa.gov < /dev/null") if !nomail;
#system("mutt -s \"$subject_korean\" -a $pngfile_korean Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov < /dev/null") if !nomail;
#system("mutt -s \"$subject_korean\" -a $pngfile_korean Evan.Howell\@noaa.gov < /dev/null") if !nomail;
print("$subject_korean\n") if $verbose;

##########################################################################
# Clean up

system("rm temp*.png");
system("rm temp*.grd");
system("rm temp.ps");
system("rm u.grd");
system("rm v.grd");
system("rm mag.grd");

system("rm $contfile") if (-e $contfile);
system("rm $contpsfile") if (-e $contpsfile);

##########################################################################
# Done, Subroutines below
##########################################################################
sub getuvfiles ($) {
   my $herenowtime = shift;
   #Find most recent ufile

    $ufile = ""; $count = 0;
#Need to fix this so I can calculate based on the gacfile not the latest file.
    until ($ufile =~ /AV/) {
       my $templocaltime = time(); my $tempuvtime = $templocaltime - 60*60*24*$count;
       my $tempuvtimecal = strftime("%Y%j", localtime($tempuvtime));
       $ufile = `find /s03/aviso/data/weekly/ -name *${tempuvtimecal}_u.grd -print`;
       #force specific ufile
       #$ufile = "/s03/aviso/data/weekly/AV2012040_2012046_u.grd";
       $count++;
    }
    chomp($ufile);
   ($vfile = $ufile) =~ s/_u/_v/;
   $shortcurrfile = basename($ufile);
   $temp1 = substr($shortcurrfile,6,3);
   $temp2 = substr($shortcurrfile,2,4);
   $outtime = timelocal_nocheck(0,0,0,$temp1,0,$temp2);
   ($second, $minute, $hour, $dayOfMonth, $month, $yearOffset, $dayOfWeek, $dayOfYear, $daylightSavings) = localtime($outtime);
   $temp = $yearOffset;
   $month = $month +1; $year = $yearOffset + 1900;
   #$sccday = "$month/$dayOfMonth/$year";
   $sccday = strftime("%d%b%Y", localtime($outtime));
   $temp1 = substr($shortcurrfile,14,3);
   $temp2 = substr($shortcurrfile,10,4);
   $outtime = timelocal_nocheck(0,0,0,$temp1,0,$temp2);
   ($second, $minute, $hour, $dayOfMonth, $month, $yearOffset, $dayOfWeek, $dayOfYear, $daylightSavings) = localtime($outtime);
   $temp = $yearOffset;
   $month = $month +1; $year = $yearOffset + 1900;
   #$eccday = "$month/$dayOfMonth/$year";
   $eccday = strftime("%d%b%Y", localtime($outtime));
}

sub getvals {
   open(OUTFILE, ">temp.txt");
   for (my $i = 181; $i <= 214; $i=$i+3) {
      $line = `grep "^$i	" $contfile`;
      chomp($line);
      ($lon, $lat, $contour) = split(" ", $line);
#      $lat++; 
      for (my $j = $lat; $j <= 40; $j++) {
#         system("echo $i $j | $GMTDIR/psxy -Jm -R -O -K -W2/0/0/0 -Sl0.3/* -G255/0/0>> $psfile");
         $ii=$i+4;
         $ij=$i-4;
         if ($lat > 20) {
            print OUTFILE "$i $lat \n$ii 40\n>\n>\n$ij 40\n$i $lat\n>\n";
         }
      }
   }
   system("$GMTDIR/psxy temp.txt -Jm -R -O -K -W4/0/0/0to -A -M >> $psfile");
}

sub buildcptfile {
   my $div = 3;
   my $temp = `$GMTDIR/grd2xyz -ZTLa -R$range temp.grd | $GMTDIR/minmax -I$div/$div -C`;
   (my $x, my $y) = split(" ", $temp);
   system("$GMTDIR/makecpt -C$WORKDIR/matlab -T$x/$y/$div -Z > sst.cpt");
   #For greyscale
   #system("$GMTDIR/makecpt -Cgray -T$x/$y/$div -Z > sst.cpt");
}
