#!/usr/bin/env python

# This is a python script to get the phenology of the fronts
#

import os, sys,linecache

#Set variables
GMTDIR = "/usr/local/gmt/bin"
WORKDIR = "/home/ehowell/projects/Turtle_Front/TW0708"

os.system('%s/gmtset DEGREE_FORMAT 3'%(GMTDIR))
os.system('%s/gmtset BASEMAP_TYPE plain'%(GMTDIR))
os.system('%s/gmtset LABEL_FONT_SIZE 16'%(GMTDIR))
os.system('%s/gmtset COLOR_NAN 255/255/255'%(GMTDIR))

outfile = 'phenology.csv'

#look to see if phenology file exists. If it does then continue
#on from last file
os.system('ls /s03/gac/data/3day/AG*.grd > gacfiles')
if os.path.exists('phenology.csv'):
    existdata = os.popen('cat %s'%(outfile)).readlines() #read in file
    endline = existdata[-1].rstrip() # get last line
    temp = endline.split()
    sedate = temp[0]
    eedate = int(temp[0])+2
    scdate = os.popen('e2d -s %s'%(sedate)).read()
    sjdate = os.popen('d2j -f -s %s'%(scdate)).read()
    ecdate = os.popen('e2d -s %d'%(eedate)).read()
    ejdate = os.popen('d2j -f -s %s'%(ecdate)).read()
    gacfile = 'AG%s_%s_sst.grd'%(sjdate,ejdate)
    files = os.popen('grep -A1000000 %s gacfiles'%(gacfile)).readlines()
    if len(files) > 1:
        files = files[1:len(files)]
        phenfile = open('phenology.csv','a') #open for appending
    else:
        print 'Time series is up to date'
        sys.exit()
else:
    print 'no'
    existdata = [];
    gacfile = 'AG2004245_2004247_sst.grd'
    files = os.popen('grep -A1000000 %s gacfiles'%(gacfile)).readlines()
    phenfile = open('phenology.csv','w') #open as new file


#psfile = "example.ps"
#pngfile = "TW${nowtime}_image.png"

#get filelist
#filesraw = os.popen('%s/listgac'%(WORKDIR)).read()
#files = filesraw.split()
#files = files[0:4]


#Loop through files
for gacfile in files:
    gacfile = gacfile.rstrip()
    shortfile = os.path.basename(gacfile)
    jdate = shortfile[4:9]
    cdate = os.popen('j2d -l -s %s'%(jdate)).read()
    edate = os.popen('d2e -s %s'%(cdate)).read()
    dateobj = cdate.split('/')
    year = dateobj[2]
    month = dateobj[0]
    day = dateobj[1]

#Get contours
    range = "190/220/27/50" # New range

    os.system("%s/grdcut %s -R%s -Gtemp.grd"%(GMTDIR,gacfile,range))
    ##system("%s/grdmath temp.grd 9 MUL 5 DIV 32 ADD = temp.grd"%(GMTDIR));

    os.system("%s/grdfilter temp.grd -R%s -D0 -Fm2 -I0.5/0.5 -Gtemp2.grd"%(GMTDIR,range))
    os.system("%s/grdcontour temp2.grd -Jm -R -O -K -A1 -Dcont -Q10 -L17.9/18.1 -W5/0/0/0 >> temp.ps"%(GMTDIR))
    rawdata = open('cont_18_0.xyz').read()
    data = rawdata.split('\n')
    lat200 = 'NaN'
    lat215 = 'NaN'
    for datapoint in data:
        if datapoint[0:4] == '200\t':
            temp = datapoint.split('\t')
            lat200 = temp[1]

        if datapoint[0:4] == '215\t':
            temp = datapoint.split('\t')
            lat215 = temp[1]

    print shortfile,edate,year,month,day,lat200,lat215
    phenfile.write('%s %s %s %s %s %s\n'%(edate,year,month,day,lat200,lat215))

phenfile.close()
#Add datestamps
#system("echo $now_string $tom_string\n");

#system("$GMTDIR/psbasemap -Jm -R$range -Bf2.5a5g5/f1.25a2.5g2.5wesn -O -K >> $psfile");

#system("convert -resize 500x386 $pngfile $WORKDIR/today_mid.png");
#system("convert -resize 150x116 $pngfile $WORKDIR/today_thumb.png");


##########################################################################
# Start the imagemagick conversions
#system("cp $pngfile $WORKDIR/today.png");
#system("cp $pngfile $XFERDIR/$pngfile");
#system("cp $pngfile $XFERDIR/today.png");
#system("cp $WORKDIR/today_mid.png $XFERDIR/today_mid.png");
#system("cp $WORKDIR/today_thumb.png $XFERDIR/today_thumb.png");

#system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov,sean\@pop-hawaii.com < /dev/null");
#system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov,Walter.Machado\@noaa.gov < /dev/null");
#system("mutt -s \"$subject\" -a $pngfile Evan.Howell\@noaa.gov < /dev/null");
#system("display $pngfile");
##########################################################################
# Clean up

#system("rm temp*.png");
#system("rm temp*.grd");
#system("rm temp.ps");
